#ifndef SETTINGS_H
#define SETTINGS_H


// THIS FILE CONTAINS ALL OF THE CONFIGURATION SETTINGS FOR THE COMPILATION
// ADDITIONALLY, ANY DEFINES ARE HERE


// SETTINGS ----------------------------------------------------------------------


// DEFINES THAT THE PROGRAM SHOULD BE COMPILED FOR A DEVELOPER
// THIS SHOWS LOGS AND SOME OTHER INFORMATION
#define DEV

// REMOVES ALL LOGS THAT ARE CONSIDERED TO APPEAR FREQUENTLY
// BY ENABLING THIS, YOU ACKNOWLEGDE THAT YOU ARE MISSING OUT ON POTENTIALLY IMPORTANT DATA
#define REMOVE_FREQUENT_LOGS

// ENABLED THE OPTION TO BLOCK THE GAME'S FUNCTION IF YOU DO NOT HAVE A LICENSE
#define FUNNY

// DISABLED LOGGING DURING TESTING
// #define DISABLE_TESTING_LOGS


// DEFINITIONS -------------------------------------------------------------------


// the max recursive depth to search when loading a directory
#define MAX_FILE_SYSTEM_DEPTH 5


#endif  // SETTINGS_H